#!/usr/bin/env bash
#
# This script will alert when battery is less than 20% and discharging
# Created by Daniel Neemann

while :; do 
	n=$(cat /sys/class/power_supply/BAT0/capacity)
	y=$(cat /sys/class/power_supply/BAT0/status)
	if [ "$n" -lt "20" ] && [ "$y" = "Discharging" ]; then
	    notify.sh -r 1 -t 0 "Battery $n%"
	fi
	sleep 5m
done
