#!/usr/bin/env bash
#
# set system colors from colorlovers.com
# requires: jq, wal
#
# author: daniel neemann (@zzzeyez)

keyword=""
amount="20"
entry="$((RANDOM%$amount))"
bg="303030"
fg="ffffff"

random() {
	dir="${HOME}/.config/wal/colorschemes/dark"
	n_files=`/bin/ls -1 "$dir" | wc -l | cut -f1`
	rand_num=`awk "BEGIN{srand();print int($n_files * rand()) + 1;}"`
	file=`/bin/ls -1 "$dir" | sed -ne "${rand_num}p"`
	path=`cd $dir && echo "$PWD/$file"` # Converts to full path.  
	wal --theme "$path" -q
	if [[ "$notify" ]] ; then
		notify-send "$file loaded"
	fi
}

colorlovers() {
	# get colorlovers palette
	url="http://www.colourlovers.com/api/palettes/top&format=json&numResults=$amount&keywords=$keyword"
	json=$(curl -s "$url")
	username=$(echo "$json" | jq ".[$entry] | .userName" | tr -d '"')
	title=$(echo "$json" | jq ".[$entry] | .title" | tr -d '"')
	color1=$(echo "$json" | jq ".[$entry] | .colors | .[0]" | tr -d '"')
	color2=$(echo "$json" | jq ".[$entry] | .colors | .[1]" | tr -d '"')
	color3=$(echo "$json" | jq ".[$entry] | .colors | .[2]" | tr -d '"')
	color4=$(echo "$json" | jq ".[$entry] | .colors | .[3]" | tr -d '"')
	color5=$(echo "$json" | jq ".[$entry] | .colors | .[4]" | tr -d '"')
}

setwal() {
	# create wal theme
	echo '{
	"wallpaper": "",
	"alpha": "100",
	"special": { 
	"background": "#'"$bg"'", 
	"foreground": "#'"$fg"'", 
	"cursor": "#'"$fg"'" 
	}, 
	"colors": { 
	"color0": "#'"$bg"'", 
	"color1": "#'"$color1"'", 
	"color2": "#'"$color2"'", 
	"color3": "#'"$color3"'", 
	"color4": "#'"$color4"'", 
	"color5": "#'"$color5"'", 
	"color6": "#'"$color5"'", 
	"color7": "#'"$fg"'", 
	"color8": "#aaaaaa",
	"color9": "#'"$color1"'", 
	"color10": "#'"$color2"'", 
	"color11": "#'"$color3"'", 
	"color12": "#'"$color4"'", 
	"color13": "#'"$color5"'", 
	"color14": "#'"$color5"'", 
	"color15": "#'"$fg"'" }} ' | jq . > /tmp/colors.json
	wal --theme /tmp/colors.json -q && rm /tmp/colors.json &&
	echo "${title//[[:space:]]/}" > /tmp/colorlovers
	if [[ "$notify" ]] ; then
		notify-send "$title by $username"
	else
		echo "$title by $username"
		echo "keyword: $keyword"
	fi
}

save() {
	savename="$(cat /tmp/colorlovers)"
	cp "${HOME}/.cache/wal/colors.json" "${HOME}/.config/wal/colorschemes/dark/$savename.json" &&
	echo "colorscheme $savename saved."
	echo "to load:"
	echo "wal --theme $savename"
	if [[ "$notify" ]] ; then
		notify-send "colorscheme $savename saved"
	fi
	exit
}

flags() {
	while getopts nsrlh opt; do
		case $opt in
			n)
			notify="on"
			;;
			s)
			save
			;;
			r)
			random
			exit
			;;
			l)
			bg="fefefe"
			fg="222222"
			;;
			h)
			echo "help"
			exit
			;;
		esac
	done
	# if no flags are provided, treat as keyword
	shift "$((OPTIND-1))" 
	if [ "$1" != "-*" ] && [ "$1" ] ;
	then
		keyword="$1"	
	fi
}

if [ "$#" -ne 0 ]; then
	flags "$@"
	colorlovers &&
	setwal
else
	amount="100"
	colorlovers &&
	setwal
fi
