#!/usr/bin/env bash
# open one iterm2 window at a time

i="$(ps cax | grep iTerm2)"

if [[ ! "$i" ]] ; then
	open -a iTerm
else
	osascript -e 'tell application "iTerm" to activate' -e 'tell application "System Events" to tell process "iTerm" to keystroke "n" using command down'
fi
