#!/bin/bash
 
# author daniel neemann
# creates notifications for currently playing last.fm track
# requires jq
#
# please don't use my included api key
# generate your own at last.fm/api/account/create

last=""

 while true; do
     lastfm=`curl -s "http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=em3i3mei&api_key=e27e6814188f7fc3da7fe91703faf865&format=json"`
     artist=`echo "$lastfm" | jq ".[] | .track | .[0] | .artist " | tr -d "\#" | jq ".text" | tr -d '"'`
     track=`echo "$lastfm" | jq ".[] | .track | .[0] | .name" | tr -d '"'`
     album=`echo "$lastfm" | jq ".[] | .track | .[0] | .album " | tr -d "\#" | jq ".text" | tr -d '"'`
     current="$artist - $track"
     if [ "$last" != "$current" ]
         then
           notify-send "♫ $current"
           last="$current"
         fi
     sleep 5s;
 done
