#!/usr/bin/env bash
# fetch lyrics on macos

rm -rf /tmp/lyrics/
mkdir /tmp/lyrics
touch /tmp/lyrics/dummy
if [[ -z $1 ]] ; then
	SONG=$(mpc current)
else
	SONG=$@
fi
LYRICS=$(echo "$SONG" | sed -e 's/\(.*\)/\1/' \
	-e 's/[\.,()?\:\x27#]//g' \
	-e "s/\'//g" \
	-e 's/-//g' \
	-e 's/&/and/g' \
	-e 's/ feat .*//g' \
	-e '/remix/!s/ - .*//g' \
	-e 's/side[^:]*://g' \
	-e 's/  */ /g' \
	-e 's/ /-/g' \
	-e 's/--*/-/g' \
	-e 'y/āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ/aaaaeeeeiiiioooouuuuuuuu/' \
	|tr -d '\200-\377')-lyrics 
rm /tmp/lyrics/*
if wget -q https://genius.com/$LYRICS -O /tmp/lyrics/$LYRICS; then
	cat /tmp/lyrics/$LYRICS \
		|grep -e '<div' -e '<br>' -e '</a>' -e '</p>' \
			|tr -d "\n" \
			|sed -e 's/Check <a.*GENIUS//g' \
			-e 's/<\/p>.*//' \
			-e 's/.*<div class="lyrics">//g' \
			-e $'s/<br>/\\\n/g' \
			-e 's/{[^>]*}//g' \
			-e 's/}[^>]*>//g' \
			-e 's/<[^>]*>//g' \
			-e 's/    //g' \
			-e 's/  //g' \
			-e 's/<a.*{//g' \
			-e 's/&amp;/\&/g'
else
	echo "Could not retrive lyrics from https://genius.com/$LYRICS"
fi
rm -rf /tmp/lyrics
