#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
#
# grabs image from Unsplash and sets as wallpaper
#
# requires `wal`, `imagemagick` and `jq`
#
# requires API key from https://unsplash.com/developers
# add the API key to the end of line 18,
# uncomment line 18 and then comment line 14

source "${HOME}/.config/api_keys"
lightordark=""
background=""

getapi() {
#	unsplashapi=
	if [[ -z $unsplashapi ]]
	then
		printf \
		"\nREQUIREMENT: GET YOUR OWN API KEY AT: \n \n"
		printf "https://unsplash.com/developers \n \n"
		printf "and then use it like so: \n \n"
		printf \
		"touch \"\${HOME}/.config/api_keys\" && "
		printf \
		"echo \"unsplashapi=YOUR_API_KEY > \${HOME}/.config/api_keys\" \n \n"
		printf \
		"replace \"YOUR_API_KEY\" with your api key \n \n"
		printf \
		"(or you can manually add it to line 18 of this script) \n"
		exit
	fi	
}

searchterm() {
	keyword="$1"
}

search() {
	entry="$((RANDOM%5))"
	searchjson=$(curl -s "https://api.unsplash.com/search/photos?client_id=$unsplashapi&query=$keyword&per_page=5")
	image=$(echo "$searchjson" | jq "{results} | .[] | .[$entry] | {urls} | .[] | {full} | .[]" | tr -d '"')
}

featured() {
	entry="$((RANDOM%50))"
	featuredjson=$(curl -s "https://api.unsplash.com/photos?client_id=$unsplashapi&per_page=50")
	image=$(echo "$featuredjson" | jq ".[$entry] | {urls} | .[] | {full} | .[]" | tr -d '"')
}

bgcolor() {
	background="-b $1"
}

lightmode() {
	lightordark="-l"
}

setwallpaper() {
	wallpaperonly="true"
}

setwal() {
	if [[ -z $wallpaperonly ]]
	then
		rm "${HOME}"/.cache/wal/schemes/_tmp*
		convert "$image" /tmp/wallpaper.jpg &&
		wal -i /tmp/wallpaper.jpg -o wal-set $background $lightordark
	else
		convert "$image" /tmp/wallpaper.jpg &&
		wallpaper /tmp/wallpaper.jpg	
	fi
}

notify() {
	notify-send -i /tmp/wallpaper.jpg
}

help() {
	printf "\navailable flags: \n"
	printf "search: -s (keyword) \n"
	printf "featured: -f \n" 
	printf "background -b (hex value) \n"
	printf "light mode: -l \n"
	printf \
	"only set wallpaper (no system palette): -w \n" 
	printf "notify when done: -n \n"
	exit
}

flags() {
	while getopts hfb:lws:n opt; do
		case $opt in
			h)
			help
			;;
			f)
			getapi
			featured
			;;
			b)
			bgcolor "$OPTARG"
			;;
			l)
			lightmode
			;;
			w)
			setwallpaper
			;;
			s)
			getapi
			searchterm "$OPTARG"
			search
			;;
			n)
			notify
			;;
			*)
			help
			;;
		esac
	done
}

if [ "$#" -ne 0 ]; then
	flags "$@"
	setwal
	echo "$image"
else
	featured
	setwal
	echo "$image"
fi
