#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
#
# grabs image from Unsplash and sets as wallpaper
#
# requires `wal`, `imagemagick` and `jq`

source ${HOME}/.config/api_keys
entry="$((RANDOM%50))"
lightordark="-l"

searchterm() {
	keyword="$1"
}

search() {
	entry="$((RANDOM%5))"
	searchjson=$(curl -s "https://api.unsplash.com/search/photos?client_id=$unsplashapi&query=$keyword&per_page=5")
	image=$(echo "$searchjson" | jq "{results} | .[] | .[$entry] | {urls} | .[] | {full} | .[]" | tr -d '"')
}

featured() {
	entry="$((RANDOM%50))"
	featuredjson=$(curl -s "https://api.unsplash.com/photos?client_id=$unsplashapi&per_page=50")
	image=$(echo "$featuredjson" | jq ".[$entry] | {urls} | .[] | {full} | .[]" | tr -d '"')
}

darkmode() {
	lightordark=""
}

setwallpaper() {
	wallpaperonly="true"
}

setwal() {
	if [[ -z $wallpaperonly ]]
	then
		rm "${HOME}"/.cache/wal/schemes/_tmp*
		convert "$image" /tmp/wallpaper.jpg &&
		wal -i /tmp/wallpaper.jpg -o wal-set $lightordark
	else
		convert "$image" /tmp/wallpaper.jpg &&
		wallpaper /tmp/wallpaper.jpg	
	fi
}

notify() {
	notify-send -i /tmp/wallpaper.jpg
}

help() {
	printf "REQUIREMENT: GET YOUR API AT https://unsplash.com/developers
add your api to the top of this file in the api() section

available flags: 
search: -s (keyword) 
featured: -f 
darkmode: -d 
only set wallpaper (no system palette): -w 
notify when done: -n"
	exit
}

flags() {
		while getopts fdws:nh opt; do
		case $opt in
			f) featured
			;;
			d) darkmode
			;;
			w) setwallpaper
			;;
			s)
				searchterm "$OPTARG"
				search
			;;
			n) notify
			;;
			h) help
			;;
			*) help
			;;
		esac
	done
}

if [ "$#" -ne 0 ]; then
	flags "$@"
	setwal
	echo "$image"
else
	featured
	setwal
	echo "$image"
fi
