#! /bin/sh
# choose random file from dir

dir="$1"
n_files="$(/bin/ls -1 "$dir" | wc -l | cut -f1)"
rand_num="$(awk "BEGIN{srand();print int($n_files * rand()) + 1;}")"
file="$(/bin/ls -1 "$dir" | sed -ne "${rand_num}p")"
path="$(cd $dir && echo "$PWD/$file")" # Converts to full path.  
echo "$path"
