#!/usr/bin/env bash
#run sway

#env __GL_GSYNC_Allowed=0 \
#__GL_VRR_ALLOWED=0 \
#WLR_DRM_NO_ATOMIC=1 \
#QT_AUTO_SCREEN_SCALE_FACTOR=1 \
#QT_QPA_PLATFORM=wayland \
#QT_WAYLAND_DISABLE_WINDOWDECORATION=1 \
#GDK_BACKEND=wayland \
#XDG_CURRENT_DESKTOP=sway \
#GBM_BACKEND=nvidia-drm \
#__GLX_VENDOR_LIBRARY_NAME=nvidia \
#MOZ_ENABLE_WAYLAND=1 \
#WLR_NO_HARDWARE_CURSORS=1 \
#sway --unsupported-gpu

#export LIBVA_DRIVER_NAME=NVIDIA &&
#export XDG_SESSION_TYPE=wayland &&
#export GMB_BACKEND=nvidia-drm &&
#export __GLX_VENDOR_LIBRARY_NAME=nvidia &&
#export WLR_NO_HARDWARE_CURSORS=1 &&
#export MOZ_ENABLE_WAYLAND=1 &&
#export WLR_RENDER=vulkan &&
bash -c '__GL_GSYNC_Allowed=0 ; __GL_VRR_ALLOWED=0 ; WLR_DRM_NO_ATOMIC=1 ; export QT_AUTO_SCREEN_SCALE_FACTOR=1 ; export QT_QPA_PLATFORM=wayland ; export QT_WAYLAND_DISABLE_WINDOWDECORATION=1 ; export GDK_BACKEND=wayland ; export XDG_CURRENT_DESKTOP=sway ; export GBM_BACKEND=nvidia-drm ; export __GLX_VENDOR_LIBRARY_NAME=nvidia ; export MOZ_ENABLE_WAYLAND=1 ; export WLR_NO_HARDWARE_CURSORS=1 ; sway --unsupported-gpu'
