#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
# macos screenshot script
#
# optional dependencies: `notify-send`, `upload`

dir="$HOME/Pictures/Screenshots/$(date +'%y-%m-%d')"
file="$(date +'%H-%M-%S')"
image="$dir/$file.png"

screenshot() {
	mkdir -p "$dir"
	screencapture -i "$image"
}

notify(){
	notify-send -m "✔ Screenshot $file.png saved" -i "$image"
}

up() {
	upload "$image"
}

flags() {
	while getopts nuh opt; do
		case $opt in
			n) notify
			;;
			u) up
			;;
			h) echo "-n to notify when finished, -u to upload"
			;;
			*) echo "-n to notify, -u to upload"
			;;
		esac
	done
}

if [ "$#" -ne 0 ]; then
	screenshot
	flags "$@"
else
	screenshot
fi
