#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
# macos screenshot script
#
# optional dependencies: `notify-send`, `upload`

dir="$HOME/.cache/scr-$(date +'%y-%m-%d')"
file="$(date +'%H-%M-%S')"
image="$dir/$file.png"

screenshot() {
	mkdir -p "$dir"
	screencapture -i "$image" &&
	if [[ "$notify" ]] ; then
		notify-send -m "$file.png saved" -i "$image"
	fi
}

up() {
	if [[ "$upload" ]] ; then
		upload "$image" &&
		if [[ "$notify" ]] ; then
			notify-send "$(pbpaste) uploaded"
		fi
	fi
}

flags() {
	while getopts nuh opt; do
		case $opt in
			n) notify="on"
			;;
			u) upload="on"
			;;
			h) echo "-n to notify when finished, -u to upload"
			;;
			*) echo "-n to notify, -u to upload"
			;;
		esac
	done
}

if [ "$#" -ne 0 ]; then
	flags "$@"
	screenshot &&
	up
else
	screenshot
fi
