#!/usr/bin/env bash

. "$HOME/.cache/wal/colors.sh"

image="/tmp/solidbg.png"

case "$1" in

	"0") convert -size 5x5 xc:$color0 $image ;;
	"1") convert -size 5x5 xc:$color1 $image ;;
	"2") convert -size 5x5 xc:$color2 $image ;;
	"3") convert -size 5x5 xc:$color3 $image ;;
	"4") convert -size 5x5 xc:$color4 $image ;;
	"5") convert -size 5x5 xc:$color5 $image ;;
	"6") convert -size 5x5 xc:$color6 $image ;;
	"7") convert -size 5x5 xc:$color7 $image ;;
	"8") convert -size 5x5 xc:$color8 $image ;;
	"15") convert -size 5x5 xc:$color15 $image ;;

esac

wallpaper $image
