#!/usr/bin/env bash
#
# author daniel neemann 
# toggles bar and lastfm notifications
#
# requires `ubersicht`, `lastfm` and chunkwm

ps cax | grep bersicht > /dev/null
if [ $? -eq 0 ]; then
	ubersicht_pid=$(ps cax | grep bersicht | awk '{print $1}')
	kill $ubersicht_pid &
	chunkc set custom_bar_enabled 0
	chunkc core::unload tiling.so
	chunkc core::load tiling.so
else
	open /Applications/Übersicht.app
	if [[ -e "${HOME}/Library/Application Support/Übersicht/widgets/pecan" ]] ; then
	height="$(awk '/--pecan-chunkwm-bar:/{print $NF}' /Users/zzzeyez/Library/Application\ Support/Übersicht/widgets/pecan/style.css | tr -d ';')"
	gaps="$(awk '/--pecan-chunkwm-gaps:/{print $NF}' /Users/zzzeyez/Library/Application\ Support/Übersicht/widgets/pecan/style.css | tr -d ';')"
	chunkc set custom_bar_offset_top "$height"
	#chunkc set global_desktop_offset_gap "$gaps"
	#chunkc set global_desktop_offset_top "$gaps"
	#chunkc set global_desktop_offset_bottom "$gaps"
	#chunkc set global_desktop_offset_left "$gaps"
	#chunkc set global_desktop_offset_right "$gaps"
	#chunkc set 1_desktop_offset_top "$gaps"
	#chunkc set 1_desktop_offset_bottom "$gaps"
	#chunkc set 1_desktop_offset_left "$gaps"
	#chunkc set 1_desktop_offset_right "$gaps"
	chunkc set custom_bar_enabled 1
	chunkc core::unload tiling.so
	chunkc core::load tiling.so
	fi
fi

# to do

# incorporate this
# defaults write NSGlobalDomain _HIHideMenuBar -bool true
# but it requires all apps to close

