#!/usr/bin/env bash
sassc --style expanded "${HOME}/scripts/pollen/scss/style.scss" > "${HOME}/scripts/pollen/style.css" &
chunkborder
bash "${HOME}/scripts/pecan/wal-set" &&
source "${HOME}/.cache/wal/colors.sh"
bg="$(echo $color0 | tr -d '#' | head -c 1)"
if [[ $bg =~ [a-zA-Z] ]]; then darkmode false; else darkmode true; fi
