#!/usr/bin/env bash
# apply `wal` colors to additional programs

# chunkwm borders
#chunkborder &

# bars
#${HOME}/scripts/pecan/wal-set &>/dev/null &
#${HOME}/scripts/xanthia/wal-set &>/dev/null &

# start page
#${HOME}/scripts/pollen/wal-set &>/dev/null &

# macos highlights
highlights

# check if the background is dark and apply darkmode if so
source "${HOME}/.cache/wal/colors.sh"
bg="$(echo $color0 | tr -d '#' | head -c 1)"
if [[ $bg =~ [a-zA-Z] ]]; then darkmode false; else darkmode true; fi


# check if ubersicht is running
ps cax | grep sicht > /dev/null
if [ $? -eq 0 ]; then
		osascript -e "tell application id \"tracesOf.Uebersicht\" to refresh"
fi
