#!/usr/bin/env bash
# Changes macOS wallpaper for current workspace
# Daniel Neemann

image="/tmp/wallpaper.png"

cp $1 /tmp/wallpaper.png &&
osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/tmp/wallpaper.png"'
